### ISSUE TITLE
Core Dump of Bundler

### ISSUE THREAD

**Issue by ghost** [snavely/bundler_sfm#11]
I successfully compiled bundler(master branch) on Ubuntu12.04. I disabled ceres.

However, when I run the script I got the following error:

./RunBundler.sh: line 145:  4600 Segmentation fault      (core dumped) $BUNDLER $IMAGE_LIST --options_file options.txt > bundle/bundle.log

The last few lines of the log is:

 tri.error[755] = 0.134
  Adding match 21965 ==> 16102 [756]
 tri.error[756] = 0.065
  Adding match 21977 ==> 16109 [7

**Comment by m-vt** [comment]
@snavely
I have the same problem giving "./RunBundler.sh: line 148: 18293 Segmentation fault      (core dumped) $BUNDLER $IMAGE_LIST --options_file options.txt > bundle/bundle.log".  I disabled ceres as well.

Do you have any suggestion?

**Comment by snavely** [comment]
Can you send the contents of the output bundle.log file?

In general, bundler is not actively maintained. You may consider COLMAP as
an alternative: https://colmap.github.io/

**Comment by m-vt** [comment]
[bundle.log.zip](https://github.com/snavely/bundler_sfm/files/11360054/bundle.log.zip)

@snavely Thanks for the reply. I attached the log file.
