### ISSUE TITLE
no output files

### ISSUE THREAD

**Issue by powersa** [snavely/bundler_sfm#21]
bundler_sfm built successfully on Linux Mint 15.

When I run bundler.py on examples/kermit everything looks good and it ends with:

[- Running Bundler -]
[- Done -]

However, the bundle dir does not contain the expected output. Based on available info I expect .out and .ply files in this location.

Here's my full output, including source and log files: https://www.dropbox.com/s/f8znbru0c88ps1e/kermit.zip

Do you see anything in these files that indicates the build went wrong or a processing step fails?

**Comment by zwzmzd** [comment]
@powersa Thank you very much. I encountered the same problem and it was solved after following your advise.

PS: Someone may have to install lapack after executing above commands.

```
sudo apt-get install liblapack-dev
```

**Comment by salmankh47** [comment]
Thanks guys. @powersa I've also encountered same issue. Got solved by this post. @snavely @powersa Thank you very much

Now trying to fix scanalyze :)

**Comment by zhangguanghui1** [comment]
@powersa Thank you very much!  I encountered the same problem and it was solved after following your advise. 
PS: Use "autoremove" with caution

**Comment by andreizakaryan** [comment]
Thank you, guys. @powersa  This was the only solution on the whole internet that helped me.

**Comment by thuliu-yt16** [comment]
Thank you very mush! The only solution for the same proplem! @powersa @zwzmzd
