### ISSUE TITLE
image processing error

### ISSUE THREAD

**Issue by DirtyHarryLYL** [snavely/bundler_sfm#30]
Hi,Noah,
    I met a problem when processing images:
[- Extracting keypoints -]
sift.txt: 行 1:  6760 Segmentation fault      D:/bundler/bin/siftWin32.exe < ../           examples/dixing/IMG_0025.pgm > ../examples/dixing/IMG_0025.key
...
[- Matching keypoints (this can take a while) -]
D:/bundler/bin/KeyMatchFull.exe list_keys.txt matches.init.txt -1
Invalid keypoint file.
...
assertion "p.first != p.second" failed: file "BaseApp.h", line 271, 
function: std::vector<KeypointMatch>& MatchTable::GetMatchList(MatchIndex)
   
There is no error occur when I run the examples like kermit or ET,so I use my own picture set:
37 pictures,  5616x3744 (10MB each )
Then the error occurs, are the pictures  too large? Is the limit of sift is 4000x4000?
It looks like that the sift didn't found any keypoints, and the key file is 1K. The output contains 
Bundler.exe.stackdump:
Stack trace:
Frame        Function    Args
0000023AF00  0018007256A (0000023E3F4, 00000000007, 00100000104, 0000023DE50)
0000023AFA0  00180073D33 (00000000064, 00000000000, 000000000E4, 00000000000)
0000023B1F0  0018012DFEF (00000000002, 00000000000, 00000000002, 00000000001)
0000023B4E0  0018012AD90 (00300000000, 00000000000, 00000000000, 00000000002)
0000023B650  0018012B259 (7FF9A43106D0, 0000023C058, 001004C5314, 00000000006)
0000023B650  0018012B42C (7FF9A16714FB, 00000004048, 001802100D8, 0018012FE9C)
0000023B650  0018012B6EF (001004C5300, 001004C5314, 0000000010F, 0018021002F)
0000023B650  00180041B65 (0060005F200, 00000000608, 0060003B7E0, 00600052590)
0060003B7E0  00100456C19 (00180103FD0, 00000000000, 001004B0000, 0060004DEA8)
00000000000  00100419137 (00000000000, 00000000001, 00000000000, 0000023C060)
0000023CB50  0010041F4C9 (0018032B388, 0000023C59C, 0018014CD20, 00000000000)
0000023CB50  00100403692 (0060003BD10, 00180211196, 0000023CB50, 00180328FD0)
0000023CB50  001004BA609 (00000000000, 00000000000, 00000000030, 30001010000FF00)
0000023CBC0  00180048410 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  001800460DC (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00180046174 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace (more stack frames may be present)

 But in visualSFM (within bundler) everything looks good.Can you help me?
Thx

**Comment by snavely** [comment]
The images are probably too large. Try resizing them to < 4000 pixels on
the longest side.

Noah

**Comment by DirtyHarryLYL** [comment]
Thank you, Noah.
lyl
