### ISSUE TITLE
Bundler on Ubuntu 14.04 LTS (core dumped)

### ISSUE THREAD

**Issue by BeebBenjamin** [snavely/bundler_sfm#34]
Hi, when I try to run bundler, it gets right to [- Matching keypoints (this can take a while)-] and then it crashes with the following error message.

[- Running Bundler -]
bundler: BaseApp.h:271: std::vector<KeypointMatch>& MatchTable::GetMatchList(MatchIndex): Assertion `p.first != p.second' failed.
/home/richard/github/bundler_sfm/RunBundler.sh: line 148:  7552 Aborted                 (core dumped) $BUNDLER $IMAGE_LIST --options_file options.txt > bundle/bundle.log
[- Done -]

Any idea what might cause this error?

**Comment by snavely** [comment]
Do your images have computed focal lengths? See question 1 of the FAQ:
http://www.cs.cornell.edu/~snavely/bundler/faq.html

Best,
Noah

**Comment by BeebBenjamin** [comment]
No.  I shall, look into this.  The photos are historical.  So I will need to calculate... That's going to be a challenge.

**Comment by snavely** [comment]
You don't need a focal length for every camera, but you need it for at
least two and the more the better.

If your photos are of manmade structures and have a lot of straight lines,
sometimes you can estimate the focal length using vanishing points.

Noah

**Comment by BeebBenjamin** [comment]
Thanks for your help!
