### ISSUE TITLE
Normal to have unused images in Bundler2PMVS conversion step?

### ISSUE THREAD

**Issue by changchuming** [snavely/bundler_sfm#37]
Hi,

I'm currently working on a project which uses Bundler, and I noticed that during the Bundler2PMVS conversion step and thereafter not every image gets converted and used. Is this behaviour normal? The resulting model is also heavily skewed to one side, i.e. all the points in the point cloud are from images taken from one direction. I've listed the relevant lines below, where it reads 31 images but only writes 11. Hope you can help with this, thanks!

> 
> Performing Bundler2PMVS conversion...
> [ReadBundleFile] Bundle version: 0.300
> [ReadBundleFile] Reading 31 images and 1534 points...
> [GetJPEGDimensions] File 1468938040522.jpg: ( 1200 , 900 )
> [GetJPEGDimensions] File 1468938039313.jpg: ( 1200 , 900 )
> [GetJPEGDimensions] File 1468938038490.jpg: ( 1200 , 900 )
> [GetJPEGDimensions] File 1468938044102.jpg: ( 1200 , 900 )
> [GetJPEGDimensions] File 1468938042958.jpg: ( 1200 , 900 )
> [GetJPEGDimensions] File 1468938045515.jpg: ( 1200 , 900 )
> [GetJPEGDimensions] File 1468938048919.jpg: ( 1200 , 900 )
> [GetJPEGDimensions] File 1468938041837.jpg: ( 1200 , 900 )
> [GetJPEGDimensions] File 1468938047940.jpg: ( 1200 , 900 )
> [GetJPEGDimensions] File 1468938046721.jpg: ( 1200 , 900 )
> [GetJPEGDimensions] File 1468938050178.jpg: ( 1200 , 900 )
> 
> 
> @@ Conversion complete, execute "sh pmvs/prep_pmvs.sh" to finalize
> @@ (you will first need to edit prep_pmvs.sh to specify your bundler path,
> @@  so that the script knows where to find your
> @@  RadialUndistort and Bundle2Vis binaries)
> [ReadBundleFile] Bundle version: 0.300
> [ReadBundleFile] Reading 31 images and 1534 points...
> Undistorting image 1468938040522.jpg
> Undistorting image 1468938039313.jpg
> Undistorting image 1468938038490.jpg
> Undistorting image 1468938044102.jpg
> Undistorting image 1468938042958.jpg
> Undistorting image 1468938045515.jpg
> Undistorting image 1468938048919.jpg
> Undistorting image 1468938041837.jpg
> Undistorting image 1468938047940.jpg
> Undistorting image 1468938046721.jpg
> Undistorting image 1468938050178.jpg
> [WriteBundleFile] Writing 11 images and 1534 points...
> [ReadBundleFile] Bundle version: 0.300
> [ReadBundleFile] Reading 11 images and 1534 points...
> Num visible: 3824
> Num cameras: 11
> Finished!
>

**Comment by snavely** [comment]
Hi Chu-Ming,

It could be that not all images were reconstructable. If you look at the bundle.out file, and see cameras where all entries equal to 0.0, then Bundler wasn't able to reconstruct those cameras. That happens where there is not enough overlap between the images to reconstruct them all as a single model. I'm guessing this is what happened.

Noah

**Comment by changchuming** [comment]
Thank you for the reply and for sharing this project. I think that that is
exactly the case. I will close this since the question has been answered.
