### ISSUE TITLE
Why there're just 2 images left when pmvs?

### ISSUE THREAD

**Issue by cycyco** [snavely/bundler_sfm#59]
Hi!
Recently I try to use Bundler to build point cloud, but after enter the command 'sh.pmvs/prep_pmvs.sh',it only writes 2 imgaes, and failed to build point cloud. I thought there might be not enough overlap between the images, but it still happened after I try other several datasets. I hope that you can help me with this ?Thanks!

```
[ReadBundleFile] Bundle version: 0.300
[ReadBundleFile] Reading 102 images and 3752 points...
Undistorting image ./IMG_5882.jpg
Undistorting image ./IMG_5890.jpg
[WriteBundleFile] Writing 2 images and 3752 points...
Running Bundle2Vis to generate vis.dat

[ReadBundleFile] Bundle version: 0.300
[ReadBundleFile] Reading 2 images and 3752 points...
Num visible: 7504
Num cameras: 2

Reading bundle...2 cameras -- 3752 points in bundle file
***********
2 cameras -- 3752 points
Reading images: **
Set widths/heights...done	0 secs
done	0 secs
slimNeighborsSetLinks...done	0 secs
mergeSFM...***********resetPoints...done
Rep counts: 3752 -> 147  	0 secs
setScoreThresholds...done	0 secs
sRemoveImages... **
Kept: 0 1 

Removed: 
sRemoveImages: 2 -> 2	0 secs
slimNeighborsSetLinks...done	0 secs

Cluster sizes: 
2 
Adding images: 
0 
Image nums: 2 -> 2 -> 2
Divide: 
done	0 secs
1 images in vis on the average
```

**Comment by snavely** [comment]
What output file from bundler are you using as the input to PMVS? If you
are using bundle.out, could you check how many cameras are actually
reconstructed in that file? (If lots of entries in the bundle.out file are
zeros, that indicates that few images were reconstructed. You can also look
at the log file in the bundle output directory.)

Noah

**Comment by cycyco** [comment]
@snavely Thanks for suggestion. I've check them and found there're 68 cameras just as many as the images I used.It seems normal.I still can't figure out what's the problem. 
Here's the bundle.log file. 
[bundle.log](https://github.com/snavely/bundler_sfm/files/1546529/bundle.log)

**Comment by NGakki** [comment]
I have the same problem. Have you solved it?

**Comment by snavely** [comment]
@cycyco Sorry for the delay... it looks like you are reading the unintended .out file in the bundle directory. You should be looking for bundle.out, and not, for instance, bundle.init.out or bundle_002.out.
