### ISSUE TITLE
How to use Bundler with stereo images

### ISSUE THREAD

**Issue by Tariq-Abuhashim** [snavely/bundler_sfm#60]
Is there away to enforce map scale from a calibrated stereo baseline or extrinsics into bundler?

**Comment by snavely** [comment]
Unfortunately there is currently no way to enforce scale from such
calibration information inside Bundler. Your best bet would be to do a
least squares solve for the scale factor as a post-process after running
Bundler.

**Comment by Tariq-Abuhashim** [comment]
Thanks.
