### ISSUE TITLE
Assert in MatchTracks.cpp

### ISSUE THREAD

**Issue by razco** [snavely/bundler_sfm#62]
I fall in the following assert:
assert(key < (int) img_data.m_keys.size());
at line 135

when running on /examples/kermit like so:
```
cd examples/kermit
../../utils/bundler.py --verbose --no-parallel
```
The compilation went smooth and I added bin to the LD_LIBRARY_PATH
Did I miss something?

Thanks

**Comment by snavely** [comment]
Perhaps your sift binary is not installed correctly? Could you send a full log of what is printed when you run the bundler.py script from a fresh data directory?
