### ISSUE TITLE
New to bundler

### ISSUE THREAD

**Issue by villa9393** [snavely/bundler_sfm#63]
Hi,

I am new to bundler.
I have downloaded the zip code.
May I know isit possible and how is it for me to install the bundler_sfm using cygwin in windows?
Many thanks

JayH

**Comment by snavely** [comment]
Yes, you can run Bundler using cygwin. Have you tried following the steps
in the "Before you Begin" section of the README file? See here:
https://github.com/snavely/bundler_sfm/#before-you-begin
