### ISSUE TITLE
Could not generate bundle.out by RunBundler.sh

### ISSUE THREAD

**Issue by veritasUF** [snavely/bundler_sfm#69]
The environment is Win10 + cygwin. The hole project is  well-built. When I run ../../RunBundler.sh in /examples/ET, the console output looks quite normal but there's not bundle.out under Directory Bundle.
The log file: 
[bundle.log](https://github.com/snavely/bundler_sfm/files/2480222/bundle.log)

**Comment by snavely** [comment]
This might be a problem in a low-level numerics library. Can you run the
program inside gdb and see where it crashes? E.g., from the data directory,
run

> gdb --args bundler list.txt --options_file options.txt

Then type hit 'run' or 'r' to run the program. It will probably segfault at
some point, at which you can type "bt" to see a stack trace, which you can
send to me.

Noah

**Comment by veritasUF** [comment]
> This might be a problem in a low-level numerics library. Can you run the program inside gdb and see where it crashes? E.g., from the data directory, run
> gdb --args bundler list.txt --options_file options.txt
> Then type hit 'run' or 'r' to run the program. It will probably segfault at some point, at which you can type "bt" to see a stack trace, which you can send to me. Noah
> […](#)

Gdb shows that something is wrong with openblas which is automatically installed by cygwin.
Problem has been solves, thanks.

**Comment by snavely** [comment]
Glad to hear the problem has been fixed. Can you comment on what the fix was, in case others have this same issue?

**Comment by veritasUF** [comment]
Stack trace shows that there is something wrong with /bin/cygblas-0.dll. So I just rename this file and reinstalled openblas from openblas.net.

**Comment by snavely** [comment]
Thanks for the comment.
